version: '3.8'

services:
  kong:
    image: kong:3.6
    container_name: kong-gateway
    restart: unless-stopped
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
      KONG_LOG_LEVEL: notice
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/null
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000,0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 127.0.0.1:8001,127.0.0.1:8444 ssl
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_ADMIN_TOKEN: ${KONG_ADMIN_TOKEN:-change-me}
      KONG_PLUGINS: bundled
      KONG_REAL_IP_HEADER: X-Forwarded-For
      KONG_REAL_IP_RECURSIVE: 'on'
      KONG_NGINX_WORKER_PROCESSES: '2'
    ports:
      - '8088:8000'
      - '8443:8443'
      - '127.0.0.1:8001:8001'
      - '127.0.0.1:8444:8444'
      - '8100:8100'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml:ro
    healthcheck:
      test: ['CMD', 'kong', 'health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - upstream

networks:
  upstream:
    external: true
    name: ${KONG_UPSTREAM_NETWORK:-chatshopmindai2_app-network}
