_format_version: "3.0"
_comment: "Minimal Kong declarative configuration"

services:
  - name: example-service
    url: http://httpbin.org/anything
    routes:
      - name: example-route
        paths:
          - /example
        strip_path: true